name: Generate latest.html from feed.xml

on:
  push:
    paths:
      - feed.xml
      - html_generator.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install BeautifulSoup
        run: pip install beautifulsoup4

      - name: Run html_generator.py
        run: python html_generator.py

      - name: Commit latest.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.html
          git commit -m "🔄 Auto-generate latest.html from feed.xml" || echo "Nothing to commit"
          git push
